# language `ghc` drags in old ghc versions
# language `generic` drags in too many others deps
# language `c` is lighter weight, and is fine since we declare most of our own deps
language: c

sudo: false

# cache only works if sudo is false
# this will attempt to cache the contents of the specified directories between
# runs to speed up install times
cache:
    directories:
        - $HOME/.stack
        - $HOME/.cabal
        - $HOME/.ghc

# clean up anything we don't want to cache
# log and index files aren't worth caching
# Note: this should be safe as cabal should still do an install
#       if a newer version of a dependency is available
before_cache:
    - rm -f $HOME/.cabal/logs/*.log
    - rm -f $HOME/.cabal/packages/00-index*
    - rm -f $HOME/.cabal/packages/01-index*
    - rm -f $HOME/.cabal/packages/build-reports.log

# using llvm from
#   https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm
#   https://launchpad.net/~h-rayflood/+archive/ubuntu/gcc-upper
#   https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm-upper
addons:
    apt:
        sources:
            - sourceline: 'ppa:h-rayflood/llvm'
            - sourceline: 'ppa:h-rayflood/gcc-upper'
            - sourceline: 'ppa:h-rayflood/llvm-upper'
        packages:
            - llvm-3.5-dev
            - llvm-3.5-runtime
            - llvm-3.5

os:
  #  - linux
  - osx

before_install:
    # put llvm-3.5 at the front of the path, ahead of any llvm-3.4
    - export PATH=/usr/lib/llvm-3.5/bin:$PATH
    # Install Stack
    - curl -sSL https://get.haskellstack.org/ | sh
    - |
      # Configure the build to use Stack
      cat > make/config-override.mk <<EOF
      BUILDFLAVOUR	= devel
      STACK   = stack --resolver lts-11.2
      GHC     = $(STACK) ghc --
      GHCI    = $(STACK) ghci --
      HADDOCK = $(STACK) exec haddock --
      DEPS_INSTALLER = $(STACK)
      EOF

install:
    - make setup

script:
    - make clean
    - make
    - make war

